// src/shop_data.ts

interface Product {
  id: number;
  name: string;
  imageUrl: string;
  price: number;
  description?: string; // Optional if not every product has a description
  category: string;
  date?: string; // Optional property for date
  stock: number; // Number of items in stock
  onSale: boolean; // Indicates if the product is on sale
  featured: boolean; // Indicates if the product is featured
  specifications: {
    material: string;
    sleeveLength: string;
    fit: string;
    careInstructions: string;
  };
  reviews: {
    name: string;
    date: string;
    rating: number;
    comment: string;
  }[];
}

const SHOP_DATA: Product[] = [
  {
    id: 1,
    name: "Brown Brim",
    imageUrl: "https://i.ibb.co/ZYW3VTp/brown-brim.png",
    price: 25,
    description: "A stylish brown brim hat.",
    category: "Clothing",
    date: "2024-01-05",
    stock: 20,
    onSale: false,
    featured: true,
    specifications: {
      material: "Wool",
      sleeveLength: "N/A",
      fit: "Regular",
      careInstructions: "Hand wash only",
    },
    reviews: [
      {
        name: "John Doe",
        date: "2024-01-10",
        rating: 4,
        comment: "Great hat, fits perfectly.",
      },
      {
        name: "Jane Smith",
        date: "2024-01-12",
        rating: 5,
        comment: "Love the style and quality.",
      },
    ],
  },
  {
    id: 2,
    name: "Blue Beanie",
    imageUrl: "https://i.ibb.co/ypkgK0X/blue-beanie.png",
    price: 18,
    description: "A warm blue beanie.",
     category: "Clothing",
    date: "2024-01-10",
    stock: 50,
    onSale: true,
    featured: false,
    specifications: {
      material: "Wool",
      sleeveLength: "N/A",
      fit: "Regular",
      careInstructions: "Hand wash only",
    },
    reviews: [
      {
        name: "John Doe",
        date: "2024-01-10",
        rating: 4,
        comment: "Great hat, fits perfectly.",
      },
      {
        name: "Jane Smith",
        date: "2024-01-12",
        rating: 5,
        comment: "Love the style and quality.",
      },
    ],
  },
  {
    id: 3,
    name: "Brown Cowboy",
    imageUrl: "https://i.ibb.co/QdJwgmp/brown-cowboy.png",
    price: 35,
    description: "A rugged brown cowboy hat.",
     category: "Clothing",
    date: "2024-01-20",
    stock: 15,
    onSale: false,
    featured: false,
    specifications: {
      material: "Wool",
      sleeveLength: "N/A",
      fit: "Regular",
      careInstructions: "Hand wash only",
    },
    reviews: [
      {
        name: "John Doe",
        date: "2024-01-10",
        rating: 4,
        comment: "Great hat, fits perfectly.",
      },
      {
        name: "Jane Smith",
        date: "2024-01-12",
        rating: 5,
        comment: "Love the style and quality.",
      },
    ],
  },
  {
    id: 4,
    name: "Grey Brim",
    imageUrl: "https://i.ibb.co/RjBLWxB/grey-brim.png",
    price: 25,
    description: "A sleek grey brim hat.",
     category: "Clothing",
    date: "2024-01-18",
    stock: 30,
    onSale: true,
    featured: false,
    specifications: {
      material: "Wool",
      sleeveLength: "N/A",
      fit: "Regular",
      careInstructions: "Hand wash only",
    },
    reviews: [
      {
        name: "John Doe",
        date: "2024-01-10",
        rating: 4,
        comment: "Great hat, fits perfectly.",
      },
      {
        name: "Jane Smith",
        date: "2024-01-12",
        rating: 5,
        comment: "Love the style and quality.",
      },
    ],
  },
  {
    id: 5,
    name: "Green Beanie",
    imageUrl: "https://i.ibb.co/YTjW3vF/green-beanie.png",
    price: 18,
    description: "A cozy green beanie.",
     category: "Clothing",
    date: "2024-01-25",
    stock: 40,
    onSale: false,
    featured: true,
    specifications: {
      material: "Wool",
      sleeveLength: "N/A",
      fit: "Regular",
      careInstructions: "Hand wash only",
    },
    reviews: [
      {
        name: "John Doe",
        date: "2024-01-10",
        rating: 4,
        comment: "Great hat, fits perfectly.",
      },
      {
        name: "Jane Smith",
        date: "2024-01-12",
        rating: 5,
        comment: "Love the style and quality.",
      },
    ],
  },
  {
    id: 6,
    name: "Palm Tree Cap",
    imageUrl: "https://i.ibb.co/rKBDvJX/palm-tree-cap.png",
    price: 14,
    description: "A cool palm tree cap.",
     category: "Clothing",
    date: "2024-02-01",
    stock: 10,
    onSale: false,
    featured: false,
    specifications: {
      material: "Wool",
      sleeveLength: "N/A",
      fit: "Regular",
      careInstructions: "Hand wash only",
    },
    reviews: [
      {
        name: "John Doe",
        date: "2024-01-10",
        rating: 4,
        comment: "Great hat, fits perfectly.",
      },
      {
        name: "Jane Smith",
        date: "2024-01-12",
        rating: 5,
        comment: "Love the style and quality.",
      },
    ],
  },
  {
    id: 7,
    name: "Red Beanie",
    imageUrl: "https://i.ibb.co/bLB646Z/red-beanie.png",
    price: 18,
    description: "A vibrant red beanie.",
     category: "Clothing",
    date: "2024-01-30",
    stock: 25,
    onSale: true,
    featured: false,
    specifications: {
      material: "Wool",
      sleeveLength: "N/A",
      fit: "Regular",
      careInstructions: "Hand wash only",
    },
    reviews: [
      {
        name: "John Doe",
        date: "2024-01-10",
        rating: 4,
        comment: "Great hat, fits perfectly.",
      },
      {
        name: "Jane Smith",
        date: "2024-01-12",
        rating: 5,
        comment: "Love the style and quality.",
      },
    ],
  },
  {
    id: 8,
    name: "Wolf Cap",
    imageUrl: "https://i.ibb.co/1f2nWMM/wolf-cap.png",
    price: 14,
    description: "A fierce wolf cap.",
     category: "Clothing",
    date: "2024-02-05",
    stock: 20,
    onSale: false,
    featured: true,
    specifications: {
      material: "Wool",
      sleeveLength: "N/A",
      fit: "Regular",
      careInstructions: "Hand wash only",
    },
    reviews: [
      {
        name: "John Doe",
        date: "2024-01-10",
        rating: 4,
        comment: "Great hat, fits perfectly.",
      },
      {
        name: "Jane Smith",
        date: "2024-01-12",
        rating: 5,
        comment: "Love the style and quality.",
      },
    ],
  },
  {
    id: 9,
    name: "Blue Snapback",
    imageUrl: "https://i.ibb.co/X2VJP2W/blue-snapback.png",
    price: 16,
    description: "A trendy blue snapback.",
     category: "Clothing",
    date: "2024-02-10",
    stock: 35,
    onSale: false,
    featured: false,
    specifications: {
      material: "Wool",
      sleeveLength: "N/A",
      fit: "Regular",
      careInstructions: "Hand wash only",
    },
    reviews: [
      {
        name: "John Doe",
        date: "2024-01-10",
        rating: 4,
        comment: "Great hat, fits perfectly.",
      },
      {
        name: "Jane Smith",
        date: "2024-01-12",
        rating: 5,
        comment: "Love the style and quality.",
      },
    ],
  },
  {
    id: 10,
    name: "Adidas NMD",
    imageUrl: "https://i.ibb.co/0s3pdnc/adidas-nmd.png",
    price: 220,
    description: "Comfortable and stylish Adidas NMD.",
     category: "Clothing",
    date: "2024-01-15",
    stock: 12,
    onSale: false,
    featured: true,
    specifications: {
      material: "Wool",
      sleeveLength: "N/A",
      fit: "Regular",
      careInstructions: "Hand wash only",
    },
    reviews: [
      {
        name: "John Doe",
        date: "2024-01-10",
        rating: 4,
        comment: "Great hat, fits perfectly.",
      },
      {
        name: "Jane Smith",
        date: "2024-01-12",
        rating: 5,
        comment: "Love the style and quality.",
      },
    ],
  },
  {
    id: 11,
    name: "Adidas Yeezy",
    imageUrl: "https://i.ibb.co/dJbG1cT/yeezy.png",
    price: 280,
    description: "Trendy Adidas Yeezy sneakers.",
     category: "Clothing",
    date: "2024-01-20",
    stock: 8,
    onSale: true,
    featured: false,
    specifications: {
      material: "Wool",
      sleeveLength: "N/A",
      fit: "Regular",
      careInstructions: "Hand wash only",
    },
    reviews: [
      {
        name: "John Doe",
        date: "2024-01-10",
        rating: 4,
        comment: "Great hat, fits perfectly.",
      },
      {
        name: "Jane Smith",
        date: "2024-01-12",
        rating: 5,
        comment: "Love the style and quality.",
      },
    ],
  },
  {
    id: 12,
    name: "Black Converse",
    imageUrl: "https://i.ibb.co/bPmVXyP/black-converse.png",
    price: 110,
    description: "Classic black Converse sneakers.",
     category: "Clothing",
    date: "2024-01-25",
    stock: 25,
    onSale: false,
    featured: false,
    specifications: {
      material: "Wool",
      sleeveLength: "N/A",
      fit: "Regular",
      careInstructions: "Hand wash only",
    },
    reviews: [
      {
        name: "John Doe",
        date: "2024-01-10",
        rating: 4,
        comment: "Great hat, fits perfectly.",
      },
      {
        name: "Jane Smith",
        date: "2024-01-12",
        rating: 5,
        comment: "Love the style and quality.",
      },
    ],
  },
  {
    id: 13,
    name: "Nike White AirForce",
    imageUrl: "https://i.ibb.co/1RcFPk0/white-nike-high-tops.png",
    price: 160,
    description: "Stylish white Nike AirForce.",
     category: "Clothing",
    date: "2024-01-30",
    stock: 15,
    onSale: false,
    featured: true,
    specifications: {
      material: "Wool",
      sleeveLength: "N/A",
      fit: "Regular",
      careInstructions: "Hand wash only",
    },
    reviews: [
      {
        name: "John Doe",
        date: "2024-01-10",
        rating: 4,
        comment: "Great hat, fits perfectly.",
      },
      {
        name: "Jane Smith",
        date: "2024-01-12",
        rating: 5,
        comment: "Love the style and quality.",
      },
    ],
  },
  {
    id: 14,
    name: "Nike Red High Tops",
    imageUrl: "https://i.ibb.co/QcvzydB/nikes-red.png",
    price: 160,
    description: "Eye-catching red Nike high tops.",
     category: "Clothing",
    date: "2024-02-05",
    stock: 20,
    onSale: true,
    featured: false,
    specifications: {
      material: "Wool",
      sleeveLength: "N/A",
      fit: "Regular",
      careInstructions: "Hand wash only",
    },
    reviews: [
      {
        name: "John Doe",
        date: "2024-01-10",
        rating: 4,
        comment: "Great hat, fits perfectly.",
      },
      {
        name: "Jane Smith",
        date: "2024-01-12",
        rating: 5,
        comment: "Love the style and quality.",
      },
    ],
  },
  {
    id: 15,
    name: "Nike Brown High Tops",
    imageUrl: "https://i.ibb.co/fMTV342/nike-brown.png",
    price: 160,
    description: "Cool brown Nike high tops.",
     category: "Clothing",
    date: "2024-02-10",
    stock: 18,
    onSale: false,
    featured: true,
    specifications: {
      material: "Wool",
      sleeveLength: "N/A",
      fit: "Regular",
      careInstructions: "Hand wash only",
    },
    reviews: [
      {
        name: "John Doe",
        date: "2024-01-10",
        rating: 4,
        comment: "Great hat, fits perfectly.",
      },
      {
        name: "Jane Smith",
        date: "2024-01-12",
        rating: 5,
        comment: "Love the style and quality.",
      },
    ],
  },
  {
    id: 16,
    name: "Air Jordan Limited",
    imageUrl: "https://i.ibb.co/w4k6Ws9/nike-funky.png",
    price: 190,
    description: "Limited edition Air Jordan sneakers.",
     category: "Clothing",
    date: "2024-02-15",
    stock: 5,
    onSale: false,
    featured: false,
    specifications: {
      material: "Wool",
      sleeveLength: "N/A",
      fit: "Regular",
      careInstructions: "Hand wash only",
    },
    reviews: [
      {
        name: "John Doe",
        date: "2024-01-10",
        rating: 4,
        comment: "Great hat, fits perfectly.",
      },
      {
        name: "Jane Smith",
        date: "2024-01-12",
        rating: 5,
        comment: "Love the style and quality.",
      },
    ],
  },
  {
    id: 17,
    name: "Timberlands",
    imageUrl: "https://i.ibb.co/Mhh6wBg/timberlands.png",
    price: 200,
    description: "Durable and rugged Timberlands.",
     category: "Clothing",
    date: "2024-02-20",
    stock: 10,
    onSale: true,
    featured: false,
    specifications: {
      material: "Wool",
      sleeveLength: "N/A",
      fit: "Regular",
      careInstructions: "Hand wash only",
    },
    reviews: [
      {
        name: "John Doe",
        date: "2024-01-10",
        rating: 4,
        comment: "Great hat, fits perfectly.",
      },
      {
        name: "Jane Smith",
        date: "2024-01-12",
        rating: 5,
        comment: "Love the style and quality.",
      },
    ],
  },
  {
    id: 18,
    name: "Black Jean Shearling",
    imageUrl: "https://i.ibb.co/XzcwL5s/black-shearling.png",
    price: 125,
    description: "Warm black jean shearling jacket.",
     category: "Clothing",
    date: "2024-01-15",
    stock: 22,
    onSale: false,
    featured: true,
    specifications: {
      material: "Wool",
      sleeveLength: "N/A",
      fit: "Regular",
      careInstructions: "Hand wash only",
    },
    reviews: [
      {
        name: "John Doe",
        date: "2024-01-10",
        rating: 4,
        comment: "Great hat, fits perfectly.",
      },
      {
        name: "Jane Smith",
        date: "2024-01-12",
        rating: 5,
        comment: "Love the style and quality.",
      },
    ],
  },
  {
    id: 19,
    name: "Blue Jean Jacket",
    imageUrl: "https://i.ibb.co/mJS6vz0/blue-jean-jacket.png",
    price: 90,
    description: "Classic blue jean jacket.",
     category: "Clothing",
    date: "2024-01-20",
    stock: 30,
    onSale: true,
    featured: false,
    specifications: {
      material: "Wool",
      sleeveLength: "N/A",
      fit: "Regular",
      careInstructions: "Hand wash only",
    },
    reviews: [
      {
        name: "John Doe",
        date: "2024-01-10",
        rating: 4,
        comment: "Great hat, fits perfectly.",
      },
      {
        name: "Jane Smith",
        date: "2024-01-12",
        rating: 5,
        comment: "Love the style and quality.",
      },
    ],
  },
  {
    id: 20,
    name: "Grey Jean Jacket",
    imageUrl: "https://i.ibb.co/N71k1ML/grey-jean-jacket.png",
    price: 90,
    description: "Stylish grey jean jacket.",
     category: "Clothing",
    date: "2024-01-25",
    stock: 28,
    onSale: false,
    featured: false,
    specifications: {
      material: "Wool",
      sleeveLength: "N/A",
      fit: "Regular",
      careInstructions: "Hand wash only",
    },
    reviews: [
      {
        name: "John Doe",
        date: "2024-01-10",
        rating: 4,
        comment: "Great hat, fits perfectly.",
      },
      {
        name: "Jane Smith",
        date: "2024-01-12",
        rating: 5,
        comment: "Love the style and quality.",
      },
    ],
  },
  {
    id: 21,
    name: "Brown Shearling",
    imageUrl: "https://i.ibb.co/s96FpdP/brown-shearling.png",
    price: 165,
    description: "Cozy brown shearling jacket.",
     category: "Clothing",
    date: "2024-02-01",
    stock: 15,
    onSale: false,
    featured: true,
    specifications: {
      material: "Wool",
      sleeveLength: "N/A",
      fit: "Regular",
      careInstructions: "Hand wash only",
    },
    reviews: [
      {
        name: "John Doe",
        date: "2024-01-10",
        rating: 4,
        comment: "Great hat, fits perfectly.",
      },
      {
        name: "Jane Smith",
        date: "2024-01-12",
        rating: 5,
        comment: "Love the style and quality.",
      },
    ],
  },
  {
    id: 22,
    name: "Tan Trench",
    imageUrl: "https://i.ibb.co/M6hHc3F/brown-trench.png",
    price: 185,
    description: "Elegant tan trench coat.",
     category: "Clothing",
    date: "2024-02-10",
    stock: 12,
    onSale: true,
    featured: false,
    specifications: {
      material: "Wool",
      sleeveLength: "N/A",
      fit: "Regular",
      careInstructions: "Hand wash only",
    },
    reviews: [
      {
        name: "John Doe",
        date: "2024-01-10",
        rating: 4,
        comment: "Great hat, fits perfectly.",
      },
      {
        name: "Jane Smith",
        date: "2024-01-12",
        rating: 5,
        comment: "Love the style and quality.",
      },
    ],
  },
  {
    id: 23,
    name: "White T-Shirt",
    imageUrl: "https://i.ibb.co/7yPmbkK/white-tee.png",
    price: 25,
    description: "Simple white T-shirt.",
     category: "Clothing",
    date: "2024-01-10",
    stock: 50,
    onSale: false,
    featured: false,
    specifications: {
      material: "Wool",
      sleeveLength: "N/A",
      fit: "Regular",
      careInstructions: "Hand wash only",
    },
    reviews: [
      {
        name: "John Doe",
        date: "2024-01-10",
        rating: 4,
        comment: "Great hat, fits perfectly.",
      },
      {
        name: "Jane Smith",
        date: "2024-01-12",
        rating: 5,
        comment: "Love the style and quality.",
      },
    ],
  },
  {
    id: 24,
    name: "Grey T-Shirt",
    imageUrl: "https://i.ibb.co/s5vZsjt/grey-tee.png",
    price: 30,
    description: "Stylish grey T-shirt.",
     category: "Clothing",
    date: "2024-01-15",
    stock: 45,
    onSale: true,
    featured: false,
    specifications: {
      material: "Wool",
      sleeveLength: "N/A",
      fit: "Regular",
      careInstructions: "Hand wash only",
    },
    reviews: [
      {
        name: "John Doe",
        date: "2024-01-10",
        rating: 4,
        comment: "Great hat, fits perfectly.",
      },
      {
        name: "Jane Smith",
        date: "2024-01-12",
        rating: 5,
        comment: "Love the style and quality.",
      },
    ],
  },
  {
    id: 25,
    name: "Black T-Shirt",
    imageUrl: "https://i.ibb.co/Tc9Bqkt/black-tee.png",
    price: 20,
    description: "Classic black T-shirt.",
     category: "Clothing",
    date: "2024-01-20",
    stock: 60,
    onSale: false,
    featured: true,
    specifications: {
      material: "Wool",
      sleeveLength: "N/A",
      fit: "Regular",
      careInstructions: "Hand wash only",
    },
    reviews: [
      {
        name: "John Doe",
        date: "2024-01-10",
        rating: 4,
        comment: "Great hat, fits perfectly.",
      },
      {
        name: "Jane Smith",
        date: "2024-01-12",
        rating: 5,
        comment: "Love the style and quality.",
      },
    ],
  },
  {
    id: 26,
    name: "Red T-Shirt",
    imageUrl: "https://i.ibb.co/N1tn2J6/red-tee.png",
    price: 22,
    description: "Bold red T-shirt.",
     category: "Clothing",
    date: "2024-01-25",
    stock: 55,
    onSale: true,
    featured: false,
    specifications: {
      material: "Wool",
      sleeveLength: "N/A",
      fit: "Regular",
      careInstructions: "Hand wash only",
    },
    reviews: [
      {
        name: "John Doe",
        date: "2024-01-10",
        rating: 4,
        comment: "Great hat, fits perfectly.",
      },
      {
        name: "Jane Smith",
        date: "2024-01-12",
        rating: 5,
        comment: "Love the style and quality.",
      },
    ],
  },
  {
    id: 27,
    name: "White V-Neck",
    imageUrl: "https://i.ibb.co/5vggZmQ/white-v-neck.png",
    price: 28,
    description: "White V-neck T-shirt.",
     category: "Clothing",
    date: "2024-02-01",
    stock: 40,
    onSale: false,
    featured: true,
    specifications: {
      material: "Wool",
      sleeveLength: "N/A",
      fit: "Regular",
      careInstructions: "Hand wash only",
    },
    reviews: [
      {
        name: "John Doe",
        date: "2024-01-10",
        rating: 4,
        comment: "Great hat, fits perfectly.",
      },
      {
        name: "Jane Smith",
        date: "2024-01-12",
        rating: 5,
        comment: "Love the style and quality.",
      },
    ],
  },
  {
    id: 28,
    name: "Blue Polo",
    imageUrl: "https://i.ibb.co/7nn0tDF/blue-polo.png",
    price: 35,
    description: "Comfortable blue polo shirt.",
     category: "Clothing",
    date: "2024-02-05",
    stock: 30,
    onSale: true,
    featured: false,
    specifications: {
      material: "Wool",
      sleeveLength: "N/A",
      fit: "Regular",
      careInstructions: "Hand wash only",
    },
    reviews: [
      {
        name: "John Doe",
        date: "2024-01-10",
        rating: 4,
        comment: "Great hat, fits perfectly.",
      },
      {
        name: "Jane Smith",
        date: "2024-01-12",
        rating: 5,
        comment: "Love the style and quality.",
      },
    ],
  },
  {
    id: 29,
    name: "Green T-Shirt",
    imageUrl: "https://i.ibb.co/ss3j9N4/green-tee.png",
    price: 25,
    description: "Bright green T-shirt.",
     category: "Clothing",
    date: "2024-02-10",
    stock: 50,
    onSale: false,
    featured: true,
    specifications: {
      material: "Wool",
      sleeveLength: "N/A",
      fit: "Regular",
      careInstructions: "Hand wash only",
    },
    reviews: [
      {
        name: "John Doe",
        date: "2024-01-10",
        rating: 4,
        comment: "Great hat, fits perfectly.",
      },
      {
        name: "Jane Smith",
        date: "2024-01-12",
        rating: 5,
        comment: "Love the style and quality.",
      },
    ],
  },
  {
    id: 30,
    name: "Black Leather Jacket",
    imageUrl: "https://i.ibb.co/JmPz9mz/black-leather-jacket.png",
    price: 250,
    description: "Stylish black leather jacket.",
     category: "Clothing",
    date: "2024-02-15",
    stock: 10,
    onSale: false,
    featured: true,
    specifications: {
      material: "Wool",
      sleeveLength: "N/A",
      fit: "Regular",
      careInstructions: "Hand wash only",
    },
    reviews: [
      {
        name: "John Doe",
        date: "2024-01-10",
        rating: 4,
        comment: "Great hat, fits perfectly.",
      },
      {
        name: "Jane Smith",
        date: "2024-01-12",
        rating: 5,
        comment: "Love the style and quality.",
      },
    ],
  },
  {
    id: 31,
    name: "White Dress",
    imageUrl: "https://i.ibb.co/W5b2dR4/white-dress.png",
    price: 150,
    description: "Elegant white dress.",
     category: "Clothing",
    date: "2024-01-15",
    stock: 25,
    onSale: true,
    featured: true,
    specifications: {
      material: "Wool",
      sleeveLength: "N/A",
      fit: "Regular",
      careInstructions: "Hand wash only",
    },
    reviews: [
      {
        name: "John Doe",
        date: "2024-01-10",
        rating: 4,
        comment: "Great hat, fits perfectly.",
      },
      {
        name: "Jane Smith",
        date: "2024-01-12",
        rating: 5,
        comment: "Love the style and quality.",
      },
    ],
  },
  {
    id: 32,
    name: "Black Dress",
    imageUrl: "https://i.ibb.co/vJ1nK3C/black-dress.png",
    price: 180,
    description: "Classic black dress.",
     category: "Clothing",
    date: "2024-01-20",
    stock: 20,
    onSale: false,
    featured: false,
    specifications: {
      material: "Wool",
      sleeveLength: "N/A",
      fit: "Regular",
      careInstructions: "Hand wash only",
    },
    reviews: [
      {
        name: "John Doe",
        date: "2024-01-10",
        rating: 4,
        comment: "Great hat, fits perfectly.",
      },
      {
        name: "Jane Smith",
        date: "2024-01-12",
        rating: 5,
        comment: "Love the style and quality.",
      },
    ],
  },
  {
    id: 33,
    name: "Red Dress",
    imageUrl: "https://i.ibb.co/sQJkG6W/red-dress.png",
    price: 160,
    description: "Bold red dress.",
     category: "Clothing",
    date: "2024-01-25",
    stock: 15,
    onSale: true,
    featured: true,
    specifications: {
      material: "Wool",
      sleeveLength: "N/A",
      fit: "Regular",
      careInstructions: "Hand wash only",
    },
    reviews: [
      {
        name: "John Doe",
        date: "2024-01-10",
        rating: 4,
        comment: "Great hat, fits perfectly.",
      },
      {
        name: "Jane Smith",
        date: "2024-01-12",
        rating: 5,
        comment: "Love the style and quality.",
      },
    ],
  },
  {
    id: 34,
    name: "Floral Dress",
    imageUrl: "https://i.ibb.co/6mTZGks/floral-dress.png",
    price: 140,
    description: "Lovely floral dress.",
     category: "Clothing",
    date: "2024-02-01",
    stock: 30,
    onSale: false,
    featured: false,
    specifications: {
      material: "Wool",
      sleeveLength: "N/A",
      fit: "Regular",
      careInstructions: "Hand wash only",
    },
    reviews: [
      {
        name: "John Doe",
        date: "2024-01-10",
        rating: 4,
        comment: "Great hat, fits perfectly.",
      },
      {
        name: "Jane Smith",
        date: "2024-01-12",
        rating: 5,
        comment: "Love the style and quality.",
      },
    ],
  },
  {
    id: 35,
    name: "Long Sleeve Shirt",
    imageUrl: "https://i.ibb.co/zFs3NGZ/long-sleeve.png",
    price: 45,
    description: "Comfortable long sleeve shirt.",
     category: "Clothing",
    date: "2024-01-10",
    stock: 50,
    onSale: true,
    featured: true,
    specifications: {
      material: "Wool",
      sleeveLength: "N/A",
      fit: "Regular",
      careInstructions: "Hand wash only",
    },
    reviews: [
      {
        name: "John Doe",
        date: "2024-01-10",
        rating: 4,
        comment: "Great hat, fits perfectly.",
      },
      {
        name: "Jane Smith",
        date: "2024-01-12",
        rating: 5,
        comment: "Love the style and quality.",
      },
    ],
  },
  {
    id: 36,
    name: "Short Sleeve Shirt",
    imageUrl: "https://i.ibb.co/5B4F3vR/short-sleeve.png",
    price: 40,
    description: "Casual short sleeve shirt.",
     category: "Clothing",
    date: "2024-01-15",
    stock: 45,
    onSale: false,
    featured: false,
    specifications: {
      material: "Wool",
      sleeveLength: "N/A",
      fit: "Regular",
      careInstructions: "Hand wash only",
    },
    reviews: [
      {
        name: "John Doe",
        date: "2024-01-10",
        rating: 4,
        comment: "Great hat, fits perfectly.",
      },
      {
        name: "Jane Smith",
        date: "2024-01-12",
        rating: 5,
        comment: "Love the style and quality.",
      },
    ],
  },
  {
    id: 37,
    name: "Striped Shirt",
    imageUrl: "https://i.ibb.co/XxJx2X9/striped-shirt.png",
    price: 50,
    description: "Stylish striped shirt.",
     category: "Clothing",
    date: "2024-01-20",
    stock: 30,
    onSale: true,
    featured: true,
    specifications: {
      material: "Wool",
      sleeveLength: "N/A",
      fit: "Regular",
      careInstructions: "Hand wash only",
    },
    reviews: [
      {
        name: "John Doe",
        date: "2024-01-10",
        rating: 4,
        comment: "Great hat, fits perfectly.",
      },
      {
        name: "Jane Smith",
        date: "2024-01-12",
        rating: 5,
        comment: "Love the style and quality.",
      },
    ],
  },
  {
    id: 38,
    name: "Plaid Shirt",
    imageUrl: "https://i.ibb.co/QchM3K3/plaid-shirt.png",
    price: 55,
    description: "Trendy plaid shirt.",
     category: "Clothing",
    date: "2024-01-25",
    stock: 35,
    onSale: false,
    featured: false,
    specifications: {
      material: "Wool",
      sleeveLength: "N/A",
      fit: "Regular",
      careInstructions: "Hand wash only",
    },
    reviews: [
      {
        name: "John Doe",
        date: "2024-01-10",
        rating: 4,
        comment: "Great hat, fits perfectly.",
      },
      {
        name: "Jane Smith",
        date: "2024-01-12",
        rating: 5,
        comment: "Love the style and quality.",
      },
    ],
  },
  {
    id: 39,
    name: "White Blouse",
    imageUrl: "https://i.ibb.co/BGg4S5Y/white-blouse.png",
    price: 60,
    description: "Elegant white blouse.",
     category: "Clothing",
    date: "2024-02-01",
    stock: 20,
    onSale: true,
    featured: true,
    specifications: {
      material: "Wool",
      sleeveLength: "N/A",
      fit: "Regular",
      careInstructions: "Hand wash only",
    },
    reviews: [
      {
        name: "John Doe",
        date: "2024-01-10",
        rating: 4,
        comment: "Great hat, fits perfectly.",
      },
      {
        name: "Jane Smith",
        date: "2024-01-12",
        rating: 5,
        comment: "Love the style and quality.",
      },
    ],
  },
  {
    id: 40,
    name: "Blue Blouse",
    imageUrl: "https://i.ibb.co/qyg3K5T/blue-blouse.png",
    price: 65,
    description: "Chic blue blouse.",
     category: "Clothing",
    date: "2024-02-05",
    stock: 18,
    onSale: false,
    featured: false,
    specifications: {
      material: "Wool",
      sleeveLength: "N/A",
      fit: "Regular",
      careInstructions: "Hand wash only",
    },
    reviews: [
      {
        name: "John Doe",
        date: "2024-01-10",
        rating: 4,
        comment: "Great hat, fits perfectly.",
      },
      {
        name: "Jane Smith",
        date: "2024-01-12",
        rating: 5,
        comment: "Love the style and quality.",
      },
    ],
  },
  {
    id: 41,
    name: "Levi's Jeans",
    imageUrl: "https://i.ibb.co/7t6k5Tk/levi-jeans.png",
    price: 80,
    description: "Comfortable Levi's jeans.",
     category: "Clothing",
    date: "2024-01-10",
    stock: 40,
    onSale: false,
    featured: true,
    specifications: {
      material: "Wool",
      sleeveLength: "N/A",
      fit: "Regular",
      careInstructions: "Hand wash only",
    },
    reviews: [
      {
        name: "John Doe",
        date: "2024-01-10",
        rating: 4,
        comment: "Great hat, fits perfectly.",
      },
      {
        name: "Jane Smith",
        date: "2024-01-12",
        rating: 5,
        comment: "Love the style and quality.",
      },
    ],
  },
  {
    id: 42,
    name: "Black Skinny Jeans",
    imageUrl: "https://i.ibb.co/x2MB6Wv/black-skinny-jeans.png",
    price: 75,
    description: "Trendy black skinny jeans.",
     category: "Clothing",
    date: "2024-01-15",
    stock: 35,
    onSale: true,
    featured: false,
    specifications: {
      material: "Wool",
      sleeveLength: "N/A",
      fit: "Regular",
      careInstructions: "Hand wash only",
    },
    reviews: [
      {
        name: "John Doe",
        date: "2024-01-10",
        rating: 4,
        comment: "Great hat, fits perfectly.",
      },
      {
        name: "Jane Smith",
        date: "2024-01-12",
        rating: 5,
        comment: "Love the style and quality.",
      },
    ],
  },
  {
    id: 43,
    name: "Blue Ripped Jeans",
    imageUrl: "https://i.ibb.co/C1x1X4v/blue-ripped-jeans.png",
    price: 85,
    description: "Stylish blue ripped jeans.",
     category: "Clothing",
    date: "2024-01-20",
    stock: 30,
    onSale: false,
    featured: true,
    specifications: {
      material: "Wool",
      sleeveLength: "N/A",
      fit: "Regular",
      careInstructions: "Hand wash only",
    },
    reviews: [
      {
        name: "John Doe",
        date: "2024-01-10",
        rating: 4,
        comment: "Great hat, fits perfectly.",
      },
      {
        name: "Jane Smith",
        date: "2024-01-12",
        rating: 5,
        comment: "Love the style and quality.",
      },
    ],
  },
  {
    id: 44,
    name: "Car Cover",
    imageUrl: "/images/car-cover.jpg",
    price: 29.99,
    description: "Protective cover for your car.",
    category: "Automotive",
    date: "2024-02-01",
    stock: 40,
    onSale: true,
    featured: false,
    specifications: {
      material: "Wool",
      sleeveLength: "N/A",
      fit: "Regular",
      careInstructions: "Hand wash only",
    },
    reviews: [
      {
        name: "John Doe",
        date: "2024-01-10",
        rating: 4,
        comment: "Great hat, fits perfectly.",
      },
      {
        name: "Jane Smith",
        date: "2024-01-12",
        rating: 5,
        comment: "Love the style and quality.",
      },
    ],
  },
  // Electronics
  {
    id: 45,
    name: "Smartphone",
    imageUrl: "/images/smartphone.jpg",
    price: 699.99,
    description: "Latest smartphone with high-end features.",
    category: "Electronics",
    date: "2024-01-10",
    stock: 25,
    onSale: false,
    featured: true,
    specifications: {
      material: "Wool",
      sleeveLength: "N/A",
      fit: "Regular",
      careInstructions: "Hand wash only",
    },
    reviews: [
      {
        name: "John Doe",
        date: "2024-01-10",
        rating: 4,
        comment: "Great hat, fits perfectly.",
      },
      {
        name: "Jane Smith",
        date: "2024-01-12",
        rating: 5,
        comment: "Love the style and quality.",
      },
    ],
  },
  {
    id: 46,
    name: "Wireless Headphones",
    imageUrl: "/images/wireless-headphones.jpg",
    price: 199.99,
    description: "High-quality wireless headphones with noise cancellation.",
    category: "Electronics",
    date: "2024-01-15",
    stock: 30,
    onSale: true,
    featured: false,
    specifications: {
      material: "Wool",
      sleeveLength: "N/A",
      fit: "Regular",
      careInstructions: "Hand wash only",
    },
    reviews: [
      {
        name: "John Doe",
        date: "2024-01-10",
        rating: 4,
        comment: "Great hat, fits perfectly.",
      },
      {
        name: "Jane Smith",
        date: "2024-01-12",
        rating: 5,
        comment: "Love the style and quality.",
      },
    ],
  },

  // Home
  {
    id: 47,
    name: "Sofa Set",
    imageUrl: "/images/sofa-set.jpg",
    price: 999.99,
    description: "Comfortable and stylish sofa set.",
    category: "Home",
    date: "2024-01-20",
    stock: 15,
    onSale: false,
    featured: true,
    specifications: {
      material: "Wool",
      sleeveLength: "N/A",
      fit: "Regular",
      careInstructions: "Hand wash only",
    },
    reviews: [
      {
        name: "John Doe",
        date: "2024-01-10",
        rating: 4,
        comment: "Great hat, fits perfectly.",
      },
      {
        name: "Jane Smith",
        date: "2024-01-12",
        rating: 5,
        comment: "Love the style and quality.",
      },
    ],
  },
  {
    id: 48,
    name: "Coffee Table",
    imageUrl: "/images/coffee-table.jpg",
    price: 150.0,
    description: "Elegant coffee table for your living room.",
    category: "Home",
    date: "2024-01-25",
    stock: 40,
    onSale: true,
    featured: false,
    specifications: {
      material: "Wool",
      sleeveLength: "N/A",
      fit: "Regular",
      careInstructions: "Hand wash only",
    },
    reviews: [
      {
        name: "John Doe",
        date: "2024-01-10",
        rating: 4,
        comment: "Great hat, fits perfectly.",
      },
      {
        name: "Jane Smith",
        date: "2024-01-12",
        rating: 5,
        comment: "Love the style and quality.",
      },
    ],
  },

  // Outdoor
  {
    id: 49,
    name: "Camping Tent",
    imageUrl: "/images/camping-tent.jpg",
    price: 149.99,
    description: "Durable camping tent for outdoor adventures.",
    category: "Outdoor",
    date: "2024-02-01",
    stock: 20,
    onSale: false,
    featured: true,
    specifications: {
      material: "Wool",
      sleeveLength: "N/A",
      fit: "Regular",
      careInstructions: "Hand wash only",
    },
    reviews: [
      {
        name: "John Doe",
        date: "2024-01-10",
        rating: 4,
        comment: "Great hat, fits perfectly.",
      },
      {
        name: "Jane Smith",
        date: "2024-01-12",
        rating: 5,
        comment: "Love the style and quality.",
      },
    ],
  },
  {
    id: 50,
    name: "Portable Grill",
    imageUrl: "/images/portable-grill.jpg",
    price: 89.99,
    description: "Compact portable grill for camping.",
    category: "Outdoor",
    date: "2024-02-05",
    stock: 30,
    onSale: true,
    featured: false,
    specifications: {
      material: "Wool",
      sleeveLength: "N/A",
      fit: "Regular",
      careInstructions: "Hand wash only",
    },
    reviews: [
      {
        name: "John Doe",
        date: "2024-01-10",
        rating: 4,
        comment: "Great hat, fits perfectly.",
      },
      {
        name: "Jane Smith",
        date: "2024-01-12",
        rating: 5,
        comment: "Love the style and quality.",
      },
    ],
  },

  // Beauty
  {
    id: 51,
    name: "Face Cream",
    imageUrl: "/images/face-cream.jpg",
    price: 24.99,
    description: "Nourishing face cream for healthy skin.",
    category: "Beauty",
    date: "2024-02-10",
    stock: 50,
    onSale: false,
    featured: true,
    specifications: {
      material: "Wool",
      sleeveLength: "N/A",
      fit: "Regular",
      careInstructions: "Hand wash only",
    },
    reviews: [
      {
        name: "John Doe",
        date: "2024-01-10",
        rating: 4,
        comment: "Great hat, fits perfectly.",
      },
      {
        name: "Jane Smith",
        date: "2024-01-12",
        rating: 5,
        comment: "Love the style and quality.",
      },
    ],
  },
  {
    id: 52,
    name: "Lip Balm",
    imageUrl: "/images/lip-balm.jpg",
    price: 5.99,
    description: "Hydrating lip balm with natural ingredients.",
    category: "Beauty",
    date: "2024-02-15",
    stock: 100,
    onSale: true,
    featured: false,
    specifications: {
      material: "Wool",
      sleeveLength: "N/A",
      fit: "Regular",
      careInstructions: "Hand wash only",
    },
    reviews: [
      {
        name: "John Doe",
        date: "2024-01-10",
        rating: 4,
        comment: "Great hat, fits perfectly.",
      },
      {
        name: "Jane Smith",
        date: "2024-01-12",
        rating: 5,
        comment: "Love the style and quality.",
      },
    ],
  },

  // Sports
  {
    id: 53,
    name: "Yoga Mat",
    imageUrl: "/images/yoga-mat.jpg",
    price: 39.99,
    description: "Non-slip yoga mat for your workout.",
    category: "Sports",
    date: "2024-03-01",
    stock: 25,
    onSale: false,
    featured: true,
    specifications: {
      material: "Wool",
      sleeveLength: "N/A",
      fit: "Regular",
      careInstructions: "Hand wash only",
    },
    reviews: [
      {
        name: "John Doe",
        date: "2024-01-10",
        rating: 4,
        comment: "Great hat, fits perfectly.",
      },
      {
        name: "Jane Smith",
        date: "2024-01-12",
        rating: 5,
        comment: "Love the style and quality.",
      },
    ],
  },
  {
    id: 54,
    name: "Dumbbell Set",
    imageUrl: "/images/dumbbell-set.jpg",
    price: 129.99,
    description: "Adjustable dumbbell set for home gym.",
    category: "Sports",
    date: "2024-03-05",
    stock: 15,
    onSale: true,
    featured: false,
    specifications: {
      material: "Wool",
      sleeveLength: "N/A",
      fit: "Regular",
      careInstructions: "Hand wash only",
    },
    reviews: [
      {
        name: "John Doe",
        date: "2024-01-10",
        rating: 4,
        comment: "Great hat, fits perfectly.",
      },
      {
        name: "Jane Smith",
        date: "2024-01-12",
        rating: 5,
        comment: "Love the style and quality.",
      },
    ],
  },

  // Toys
  {
    id: 55,
    name: "Building Blocks",
    imageUrl: "/images/building-blocks.jpg",
    price: 49.99,
    description: "Creative building blocks for kids.",
    category: "Toys",
    date: "2024-03-10",
    stock: 40,
    onSale: false,
    featured: true,
    specifications: {
      material: "Wool",
      sleeveLength: "N/A",
      fit: "Regular",
      careInstructions: "Hand wash only",
    },
    reviews: [
      {
        name: "John Doe",
        date: "2024-01-10",
        rating: 4,
        comment: "Great hat, fits perfectly.",
      },
      {
        name: "Jane Smith",
        date: "2024-01-12",
        rating: 5,
        comment: "Love the style and quality.",
      },
    ],
  },
  {
    id: 56,
    name: "Puzzle Game",
    imageUrl: "/images/puzzle-game.jpg",
    price: 29.99,
    description: "Challenging puzzle game for all ages.",
    category: "Toys",
    date: "2024-03-15",
    stock: 60,
    onSale: true,
    featured: false,
    specifications: {
      material: "Wool",
      sleeveLength: "N/A",
      fit: "Regular",
      careInstructions: "Hand wash only",
    },
    reviews: [
      {
        name: "John Doe",
        date: "2024-01-10",
        rating: 4,
        comment: "Great hat, fits perfectly.",
      },
      {
        name: "Jane Smith",
        date: "2024-01-12",
        rating: 5,
        comment: "Love the style and quality.",
      },
    ],
  },

  // Pets
  {
    id: 57,
    name: "Pet Bed",
    imageUrl: "/images/pet-bed.jpg",
    price: 59.99,
    description: "Comfortable bed for your furry friends.",
    category: "Pets",
    date: "2024-04-01",
    stock: 20,
    onSale: false,
    featured: true,
    specifications: {
      material: "Wool",
      sleeveLength: "N/A",
      fit: "Regular",
      careInstructions: "Hand wash only",
    },
    reviews: [
      {
        name: "John Doe",
        date: "2024-01-10",
        rating: 4,
        comment: "Great hat, fits perfectly.",
      },
      {
        name: "Jane Smith",
        date: "2024-01-12",
        rating: 5,
        comment: "Love the style and quality.",
      },
    ],
  },
  {
    id: 58,
    name: "Pet Toy",
    imageUrl: "/images/pet-toy.jpg",
    price: 14.99,
    description: "Interactive toy for pets.",
    category: "Pets",
    date: "2024-04-05",
    stock: 40,
    onSale: true,
    featured: false,
    specifications: {
      material: "Wool",
      sleeveLength: "N/A",
      fit: "Regular",
      careInstructions: "Hand wash only",
    },
    reviews: [
      {
        name: "John Doe",
        date: "2024-01-10",
        rating: 4,
        comment: "Great hat, fits perfectly.",
      },
      {
        name: "Jane Smith",
        date: "2024-01-12",
        rating: 5,
        comment: "Love the style and quality.",
      },
    ],
  },

  // Books
  {
    id: 59,
    name: "Novel",
    imageUrl: "/images/novel.jpg",
    price: 14.99,
    description: "A thrilling novel for book lovers.",
    category: "Books",
    date: "2024-04-10",
    stock: 100,
    onSale: false,
    featured: true,
    specifications: {
      material: "Wool",
      sleeveLength: "N/A",
      fit: "Regular",
      careInstructions: "Hand wash only",
    },
    reviews: [
      {
        name: "John Doe",
        date: "2024-01-10",
        rating: 4,
        comment: "Great hat, fits perfectly.",
      },
      {
        name: "Jane Smith",
        date: "2024-01-12",
        rating: 5,
        comment: "Love the style and quality.",
      },
    ],
  },
  {
    id: 60,
    name: "Cookbook",
    imageUrl: "/images/cookbook.jpg",
    price: 29.99,
    description: "Delicious recipes for home cooking.",
    category: "Books",
    date: "2024-04-15",
    stock: 50,
    onSale: true,
    featured: false,
    specifications: {
      material: "Wool",
      sleeveLength: "N/A",
      fit: "Regular",
      careInstructions: "Hand wash only",
    },
    reviews: [
      {
        name: "John Doe",
        date: "2024-01-10",
        rating: 4,
        comment: "Great hat, fits perfectly.",
      },
      {
        name: "Jane Smith",
        date: "2024-01-12",
        rating: 5,
        comment: "Love the style and quality.",
      },
    ],
  },

  // Automotive
  {
    id: 61,
    name: "Car Cover",
    imageUrl: "/images/car-cover.jpg",
    price: 29.99,
    description: "Protective cover for your car.",
    category: "Automotive",
    date: "2024-05-01",
    stock: 30,
    onSale: false,
    featured: true,
    specifications: {
      material: "Wool",
      sleeveLength: "N/A",
      fit: "Regular",
      careInstructions: "Hand wash only",
    },
    reviews: [
      {
        name: "John Doe",
        date: "2024-01-10",
        rating: 4,
        comment: "Great hat, fits perfectly.",
      },
      {
        name: "Jane Smith",
        date: "2024-01-12",
        rating: 5,
        comment: "Love the style and quality.",
      },
    ],
  },
  {
    id: 62,
    name: "Car Vacuum Cleaner",
    imageUrl: "/images/car-vacuum.jpg",
    price: 49.99,
    description: "Compact vacuum cleaner for your car.",
    category: "Automotive",
    date: "2024-05-05",
    stock: 25,
    onSale: true,
    featured: false,
    specifications: {
      material: "Wool",
      sleeveLength: "N/A",
      fit: "Regular",
      careInstructions: "Hand wash only",
    },
    reviews: [
      {
        name: "John Doe",
        date: "2024-01-10",
        rating: 4,
        comment: "Great hat, fits perfectly.",
      },
      {
        name: "Jane Smith",
        date: "2024-01-12",
        rating: 5,
        comment: "Love the style and quality.",
      },
    ],
  },
];

export default SHOP_DATA;
